import type { DemoFinding, DemoScores, DemoTopology } from '../types/demo';

const severityOrder: Record<DemoFinding['severity'], number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };

/** Builds a plain-text/markdown audit report from the live analysis session — every figure here is pulled directly from the parsed file, nothing synthesized. */
export function buildReportMarkdown(params: {
  filename: string;
  topology: DemoTopology;
  findings: DemoFinding[];
  scores: DemoScores;
  summary: string;
}): string {
  const { filename, topology, findings, scores, summary } = params;
  const sorted = [...findings].sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity]);
  const now = new Date().toISOString().replace('T', ' ').slice(0, 19);

  const lines: string[] = [];
  lines.push(`# PathVector Network Analysis Report`);
  lines.push(``);
  lines.push(`Source file: ${filename}`);
  lines.push(`Generated: ${now} UTC`);
  lines.push(`Devices: ${topology.devices.length}    Links: ${topology.links.length}    Findings: ${findings.length}`);
  lines.push(``);
  lines.push(`## Network Health: ${scores.overall}/100`);
  lines.push(`- Switching Health: ${scores.switching}`);
  lines.push(`- Routing Health: ${scores.routing}`);
  lines.push(`- Security Posture: ${scores.security}`);
  lines.push(`- Infrastructure Hygiene: ${scores.infrastructure}`);
  lines.push(``);
  lines.push(`## Executive Summary`);
  lines.push(summary || 'No AI summary available.');
  lines.push(``);
  lines.push(`## Findings (${findings.length})`);
  sorted.forEach((f) => {
    lines.push(``);
    lines.push(`### [${f.severity.toUpperCase()}] ${f.rule_id} — ${f.title}`);
    lines.push(`Affected: ${f.affected_devices.join(', ') || '—'}`);
    if (f.confidence !== null) lines.push(`AI confidence: ${f.confidence}%`);
    lines.push(f.description);
    if (f.ai_diagnosis) {
      lines.push('');
      lines.push(`AI diagnosis: ${f.ai_diagnosis}`);
    }
    if (f.evidence.length) {
      lines.push('');
      lines.push('Evidence:');
      f.evidence.forEach((e) => lines.push(`  - ${e}`));
    }
    const fixEntries = Object.entries(f.fix_commands).filter(([, cmds]) => cmds.length);
    if (fixEntries.length) {
      lines.push('');
      lines.push('Recommended fix:');
      fixEntries.forEach(([device, cmds]) => {
        lines.push(`  ${device}:`);
        cmds.forEach((c) => lines.push(`    ${c}`));
      });
    }
  });
  lines.push('');
  lines.push('---');
  lines.push('Generated by PathVector Virtualization Demo. All figures above were computed from the uploaded topology file.');
  return lines.join('\n');
}

export function downloadReport(markdown: string, filename: string) {
  const base = filename.replace(/\.(pkt|gns3|zip)$/i, '') || 'network';
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `pathvector-report-${base}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
